# Generated by Django 4.0.3 on 2023-03-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0002_alter_book_id_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=500),
        ),
    ]
