# Generated by Django 4.0.3 on 2023-03-13 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0004_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
