# Generated by Django 4.0.3 on 2023-03-15 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookss', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_review',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.TextField(),
        ),
    ]
