# Generated by Django 4.0.3 on 2023-03-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookss', '0006_book_author_review_alter_book_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='author_reivew',
        ),
    ]
