# Generated by Django 4.0.3 on 2023-03-16 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookss', '0009_alter_review_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
