# Generated by Django 4.0.3 on 2023-03-16 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookss', '0010_alter_book_author_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author_reivew',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='author_review',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookss.book'),
            preserve_default=False,
        ),
    ]
